services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: rtls
      POSTGRES_PASSWORD: rtls
      POSTGRES_DB: rtls
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "9001:9001"   # MQTT over WebSockets (opcional, para el frontend)
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  pgdata:
